{
 "title": "Seaker Alert Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total RAM Space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"ram_total\") FROM \"system_metrics\" WHERE $timeFilter\n"
    }
   ]
  },
  {
   "title": "RAM Usage Percentage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT 100 * last(\"ram_used\") / last(\"ram_total\") FROM \"system_metrics\" WHERE $timeFilter\n"
    }
   ]
  },
  {
   "title": "Disk Usage Percentage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "system_metrics",
     "query": "SELECT 100 * last(\"disk_used\") / last(\"disk_total\") FROM \"system_metrics\" WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "disk_used" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Device Uptime",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "measurement": "system_metrics",
     "query": "SELECT \"uptime\" FROM \"system_metrics\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Disk Space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "system_metrics",
     "query": "SELECT last(\"disk_total\") FROM \"system_metrics\" WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "disk_total" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "measurement": "system_metrics",
     "query": "SELECT \"disk_used\" FROM \"system_metrics\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "disk_used" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_metrics",
     "select": [
      [
       { "params": [ "ram_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "measurement": "system_metrics",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}